name: Deploy to VPS

on:
  push:
    branches:
      - issue8   # ajusta si usas otra rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP_INTRATEL }}
          port: ${{ secrets.VPS_SSH_PORT_INTRATEL }}
          username: ${{ secrets.VPS_SSH_USER_INTRATEL }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY_INTRATEL }}
          script: |
            /usr/local/bin/deploy-intratel